name: Check and Deploy library to Maven Central

on:
  push:
    branches:
      - pre-release

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Set up JDK 21
        uses: actions/setup-java@v5.0.0
        with:
          distribution: temurin
          java-version: 21
          cache: maven
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

      - name: Show project version
        run: mvn help:evaluate -Dexpression=project.version -q -DforceStdout

      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Deploy to Maven Central
        run: mvn clean deploy -P release --batch-mode
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

      - name: Configure Git
        run: |
          git config user.name "TDMinhNhat [Auto]"
          git config user.email "tdminhnhat13092003@gmail.com"

      - name: Fetch all branches
        run: git fetch origin

      - name: Merge pre-release -> main
        run: |
          git checkout main
          git merge --no-ff origin/pre-release -m "Auto-merge pre-release into main"
          git push origin main
