name: Check and Deploy library to Maven Central

on:
  push:
    branches:
      - pre-release

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: generate-database-environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Set up JDK 21
        uses: actions/setup-java@v5.0.0
        with:
          distribution: temurin
          java-version: 21
          cache: maven
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

      - name: Debug GPG
        run: |
          echo "=== Listing GPG secret keys ==="
          gpg --list-secret-keys --keyid-format LONG || true
          echo "=== Listing GPG public keys ==="
          gpg --list-keys --keyid-format LONG || true

      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Debug Maven settings
        run: |
          echo "=== Effective settings.xml ==="
          grep -A 2 "<server>" ~/.m2/settings.xml | sed 's/<password>.*<\/password>/<password>***<\/password>/'

      - name: Deploy to Maven Central
        run: mvn clean deploy -P release --batch-mode
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}

      - name: Configure Git
        run: |
          git config user.name "TDMinhNhat [Auto]"
          git config user.email "tdminhnhat13092003@gmail.com"

      - name: Fetch all branches
        run: git fetch origin

      - name: Merge pre-release -> main
        run: |
          git config user.name "TDMinhNhat [Auto]"
          git config user.email "tdminhnhat13092003@gmail.com"
      
          # Fetch all branches
          git fetch origin
      
          # Checkout pre-release and rebase onto main
          git checkout pre-release
          git rebase origin/main
      
          # Switch to main and merge pre-release
          git checkout main
          git merge --ff-only pre-release
      
          # Push changes
          git push origin main
