name: Check and Deploy library to Maven Central

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Set up JDK 21
        uses: actions/setup-java@v5.0.0
        with:
          distribution: temurin
          java-version: 21
          cache: maven
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

      - name: Show project version
        run: mvn help:evaluate -Dexpression=project.version -q -DforceStdout

      - name: Deploy to Maven Central
        run: mvn clean deploy -P release --batch-mode
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

      - name: Get Project Version
        id: project_version
        run: echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.project_version.outputs.version }}
          name: Release ${{ steps.project_version.outputs.version }}
          body: |
            🚀 New release of **generate-database**
            Version: `${{ steps.project_version.outputs.version }}`
            Changes:
            - Auto-generated release from CI/CD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
